### ISSUE TITLE
Track: Monster Slayer (Module 4)

### ISSUE THREAD

**Issue by sortedcord** [sortedcord/vue-monsterslayer#1]
## Course Project: MonsterSlayer

- [x] Project Setup
- [ ] Updating Health Bars
- [ ] Adding Special Attacks
- [ ] Adding heal functionality
- [ ] Adding game over screen
- [ ] Complete Core Functionality
- [ ] Adding battle log
